### ISSUE TITLE
Follow the Ender Eye

### ISSUE THREAD

**Issue by kebunny** [Tedyhere/Magelife3Awakenings#11]
I have not found the end yet, but I would think that just Throwing/Using The Ender Eye would complete the Advancement? I crafted the Endereye and threw it and nothing happened. I even went in creative to test it as well.

**Comment by Tedyhere** [comment]
JESUS FOR THE LOVE OF GOD! IF THE ADVANCEMENT HAS NOTHING TO DO WITH BETWEENLANDS IT IS A PLACEHOLDER! STOP REPORTING THEM
