### ISSUE TITLE
Glitch issues with crafting Table Quick Crafting

### ISSUE THREAD

**Issue by kebunny** [Tedyhere/Magelife3Awakenings#5]
I used the Quick crafting button to make some of the Ladders. After Trying to do it a couple times, I couldn't open any GUI block, I tried to save and quit, but i crashed then.

I have not played on it since my last stream and was wondering if I should put the Save in here? IDK? It's been awhile since testing back then.

**Comment by Tedyhere** [comment]
Iwould need the crash log pls.. pastebin.com... copy and paste into pasteni, hit save and post a link

**Comment by kebunny** [comment]
There was no Crash log when it crashed. It froze so i had to restart the computer. 

Here is the Clip from the Stream when it happened. 

https://clips.twitch.tv/AlluringArborealPonyTheTarFu

**Comment by Tedyhere** [comment]
I think you crashed before you even tried quick crafting, the game just became overwhelmed. If it keeps doing that either 1) don't use quick crafting or 2) increase your memory or use fast graphics and lower particles. This is not a graphics light modpack
