### ISSUE TITLE
Using Journey maps crash

### ISSUE THREAD

**Issue by kebunny** [Tedyhere/Magelife3Awakenings#6]
As I was writing a name for a waypoint it crashed to desktop putting this:

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.IllegalArgumentException: name may not be blank

**Comment by Tedyhere** [comment]
go into the logs folder.. find the latest crash log, copy all text. Go to www.pastebin.com. paste it there, save and post the link here.

**Comment by kebunny** [comment]
https://pastebin.com/2iXQ8vcL

**Comment by Tedyhere** [comment]
Ok, passing this on to Journeymap devs, until than I'm switching to mapwriter.
